### ISSUE TITLE
关于nf_register.cpp里的 tls 跟 401  这里的hook

### ISSUE THREAD

**Issue by w4454962** [actboy168/YDWE#102]
去年在初步实现内置japi的时候 稍微做了点研究 为了赶时间就先搁置了
从hook的地方来看 似乎目的很明显 是通过hook 401内存分配的函数 来 捕获 jass虚拟机初始化的时机
而hook tls 似乎仅仅是获取 jass虚拟机执行的线程id 
我用的内置方法是在地图里调用初始化的 所以 线程id 跟初始化时机都可以很简而易举的获取得到
所以这 tls的hook 似乎对兼容性比较差吧  好几个月前11平台有反挂组的说影响了11的什么鬼 也没去在意 后来神话说这东西尽可能少hook  
所以 我的问题是  这2个hook的作用我猜测的是不，如果逻辑没错的话 ，我就取消掉这2个hook  改用手动初始化即可了吧。 我取消后测试了下 并不会对japi造成影响 ，所以应该没问题吧？

**Comment by w4454962** [comment]
刚才可能是说错了  
hook 401 获取初始化的线程id 然后
hook tls 初始化 japi_add
再到401里 初始化 其他的japi_hook
大概目的也是在做初始化的准备工作吧。

**Comment by w4454962** [comment]
我的意思是 可以用更简单的方法 不一定非要hook 兼容性差的 tls吧。

**Comment by actboy168** [comment]
兼容性明显更好，至于你的问题，这不是YDWE的问题

**Comment by w4454962** [comment]
- -我逻辑没问题，确实是跟我想的一样，只是有些疑惑 就像伤害函数里 hook虚函数指针 是在搜索函数地址的情况下找到 指针 要是先被hook了 就搜索不到指针了 - - tls里也是一样吧 多个程序同时hook 就会有个会死了。。。 好吧 暂时就这样了。  我去掉后 程序正常 没问题了。

**Comment by w4454962** [comment]
刚想错了 这个地方的hook我是不需要的 然后不知道那群家伙怎么搞冲突的 我去掉后没有问题 暂时就这样了。
