### ISSUE TITLE
Bad BLP Parsing Logic

### ISSUE THREAD

**Issue by DrSuperGood** [actboy168/YDWE#106]
Looked through the BLP read logic located in file "YDWE/Development/Core/BlpConv/Blp.cpp" and it is clearly wrong. It looks like it was based on incorrect specifications that were written long ago, mostly during RoC beta.

The problems with it...
- No support for index colour content with 0, 1, 4 and 8 bit alpha.
- Incorrect parsing of the colour palette when parsing index content. The palette does not contain any alpha information and only BGR components.
- Nonsense alpha logic for index colour. The alpha logic used is based on the alpha bits field (what you incorrectly call "Flags" in the header struct). The field "PictureType" is actually unused as far as testing has shown, with current theories being it either has a meaning to Blizzard for internal use or that it was left over from early versions of RoC where it did have a meaning. It is possible it has something to do with how textures are loaded for use by the graphic API but if so it is very obscure and has no effect on most models or the UI.
- No alpha logic for JPEG content BLP. JPEG content BLP supports both 0 and 8 bit alpha, with 0 bit alpha meaning the alpha channel should be ignored but still present in the underlying 4 channel JPEG file.
- Bad default case logic. For content type other than 0 and 1 WC3 assumes 0. For alpha bits other than those supported by the content type WC3 assumes 0 bit alpha.

Currently that code will fail to correctly read many of the BLP files supported by WC3.

I have attached a series of index content BLP files that can be used for testing purposes as well as the correct decoding results. WC3 will load them all correctly with a texture identical to the png files.

[BLP Index Content Tests.zip](https://github.com/actboy168/YDWE/files/1220130/BLP.Index.Content.Tests.zip)

**Comment by actboy168** [comment]
Thanks for your work. I will fix it.

**Comment by actboy168** [comment]
> No alpha logic for JPEG content BLP. JPEG content BLP supports both 0 and 8 bit alpha, with 0 bit alpha meaning the alpha channel should be ignored but still present in the underlying 4 channel JPEG file.

Can you provide a blp of parsing errors? Thanks.

**Comment by DrSuperGood** [comment]
> Can you provide a blp of parsing errors?

I am not sure what you are asking for exactly. Within the WC3 MPQs there are JPEG content BLP files for both 0 and 8 bit alpha. The reason the other test images are useful is because WC3 does not contain any examples of 1 and 4 bit alpha index colour content BLP files, although the game engine still supports loading them.

**Comment by actboy168** [comment]
I mean a JPEG content BLP, but it will parse the error.

**Comment by DrSuperGood** [comment]
> I mean a JPEG content BLP, but it will parse the error.

What error you referring to?

**Comment by actboy168** [comment]
This error.
> No alpha logic for JPEG content BLP. JPEG content BLP supports both 0 and 8 bit alpha, with 0 bit alpha meaning the alpha channel should be ignored but still present in the underlying 4 channel JPEG file.

**Comment by DrSuperGood** [comment]
You can find files for that in the Warcraft III data MPQs. All paths below were from 1.27 and should not have changed between 1.28.6.

An example of a JPEG content BLP file with 0 alpha bits and correctly opaque alpha channel.
Abilities\Spells\Human\Blizzard\Frost3test.blp

An example of a JPEG content BLP file with 8 alpha bits.
Abilities\Spells\Human\Banish\GenericGlow2bA.blp

An example of a JPEG content BLP file with 0 alpha bits but with incorrectly transparent alpha channel in at least 1 mipmap level. All 10 mipmap levels contain at least 1 transparent pixel. A bug in WC3 means that such images do correctly ignore alpha transparency when used as UI elements, eg a command card icon, but do not when used as a model texture.
UI\Glues\Loading\Backgrounds\Campaigns\AshenvaleLocationIcons.blp

Attached is a full list of BLP files that could be extracted from 1.27. It was produced during testing of my JAVA ImageIO plugin for BLP. Note that pixmap type and sample fields can be ignored, they are used by BLP2 (World of Warcraft) and were added there for interoperability with the header type.

[All BLP.zip](https://github.com/actboy168/YDWE/files/1222473/All.BLP.zip)

**Comment by actboy168** [comment]
Thanks. I tried to fix all the problems. Are there any problems now?

**Comment by DrSuperGood** [comment]
Content type values that are not 0 or 1 should be parsed as if 0 (default case is same behaviour as 0) and not throw an error. WC3 will correctly load such files if they are formatted for JPEG content.

The BLP::LoadCompressed algorithm might not manage image size correctly (I am not sure). If the JPEG file decodes to an image bigger than that specified by the BLP header then it must be shrunk by cropping the bottom and right edges. If the JPEG image is smaller than that specified by the BLP header then it must be expanded by padding with black (transparent if alpha bit is 8, opaque if not) at the bottom and right edges.
