### ISSUE TITLE
提交一个 utf8转ansi编码的bug

### ISSUE THREAD

**Issue by w4454962** [actboy168/YDWE#109]
在ydwe里 可以设置魔兽的运行时的玩家名
当这个玩家名,在局域网测试的时候,会因为超过指定长度,而导致超过的字符被无视,从而使最后一个中文出现乱码,之后再调用base::u2a就会崩溃
比如: "遥远的拂晓"   这个名字就会出现这个情况。

**Comment by actboy168** [comment]
是抛了异常吧？

**Comment by w4454962** [comment]
崩溃之后，魔兽errors文件夹也会生成崩溃日志

**Comment by actboy168** [comment]
异常没处理就是崩溃

**Comment by w4454962** [comment]
= =意思是要自己写try捕获么，那你记得写注释。。。
