### ISSUE TITLE
最萌小汐的JAPI请求 2013-8-19

### ISSUE THREAD

**Issue by syj2010syj** [actboy168/YDWE#11]
JAPI 2013-8-19
--------------------急需----------------------
1.修改技能的学习图标
2.修改技能的关闭图标
3.修改BUFF的图标
4.修改BUFF的说明
5.修改BUFF的扩展说明

注:3-5当时测试的时候可以实现,正式版时无法实现,烦请核实

---------------------需求----------------------
6.(玩家)单位发布无目标(点目标,物体目标)指令时通过触发玩家获取命令发布者,而不是触发单位的所有者

---------------------长期----------------------
7.修改物品图标
8.修改物品(扩展)说明
9.修改物品价格
10.修改物品带的技能(CD组)
11.修改物品是否可以主动使用

注:7-11是为了脚本统一注册物品

**Comment by actboy168** [comment]
没计划
