### ISSUE TITLE
关于模型导入

### ISSUE THREAD

**Issue by thautwarm** [actboy168/YDWE#110]
有没有什么好的模型导入的方法?
blp文件前缀去除的那个。
没有的话，我今天搞了个自动脚本处理，可否pr一波？

**Comment by luciouskami** [comment]
魔兽的输入管理器有导入文件夹的功能。

**Comment by thautwarm** [comment]
@luciouskami 导入文件夹之后，blp文件的路径是需要修改的呀。要去掉前面那段，这个工作量好大。。

**Comment by actboy168** [comment]
https://github.com/syj2010syj/w3x2lni

**Comment by thautwarm** [comment]
@actboy168 木有使用文档啊...(哭

**Comment by actboy168** [comment]
简单到甚至不需要文档
