### ISSUE TITLE
lua引擎的TriggerSleepAction还是有bug

### ISSUE THREAD

**Issue by w4454962** [actboy168/YDWE#111]
将一个地图jass2lua之后，会在有多个
TransmissionFromUnitWithNameBJ 电影-播送单位消息(指定单位)
的地方出现多次循环当前函数的动作
原因可能是因为 这个BJ函数里 的等待是在 if之中进行的，然后lua引擎对等待问题可能有些水土不服。

**Comment by actboy168** [comment]
你这种表述方式等于什么都没说

**Comment by w4454962** [comment]
lua写的一个触发动作里，有多句TransmissionFromUnitWithNameBJ跟等待，会无限循环这个触发动作。

**Comment by syj2010syj** [comment]
建议你做个能简单描述问题的演示图
