### ISSUE TITLE
关于build.root导致的加载share\script\ydwe\main.lua失败

### ISSUE THREAD

**Issue by Whimsyduke** [actboy168/YDWE#112]
当前版本修改了Development\Core\LuaEngine\DllMain.cpp的BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID pReserved)，其中
                                if (fs::exists(ydwedev / "build.root")) {
					ydwe = ydwedev  / L"Component";
				}
的条件在YD处于两个不同的Bulid路径（Development\Build\bin\和Build\publish\）时都会进入但是在不同情况下获取的ydwedev 是不同的值，以目前的代码，这会导致批处理生成（Build\publish\）的YD无法正确加载share\script\ydwe下的lua脚本。正确路径是（Development\Component\share\script\ydwe）但是实际组成路径为(Component\share\script\ydwe)

**Comment by actboy168** [comment]
根目录的build.root是历史遗留产物
