### ISSUE TITLE
ydwe跟teamviewer貌似有冲突

### ISSUE THREAD

**Issue by foxphehe** [actboy168/YDWE#115]
电脑系统是win10,预装的
ydwe版本是1.31.8正式版

在公司用teamviewer连着自己电脑
或者自己电脑开着teamviewer,但是没有连接的时候
打开ydwe会在启动图之后,载入条出现之前停止工作

emmmm...大概就是这样子了

**Comment by actboy168** [comment]
既然是收费软件，你找他的客服解决好了
