### ISSUE TITLE
使用LUA的时候无法调用动态链接库dll

### ISSUE THREAD

**Issue by Hifairlady** [actboy168/YDWE#117]
请问下在使用lua脚本的时候应该如何调用自己写的dll链接库呢? 老是在require的时候提示找不到指定的文件, 可是在使用lua官方编译器的时候就没问题. dll文件不是应该放在跟lua脚本同样的地方就可以生效吗?
https://pan.baidu.com/s/1dE5lyST

**Comment by Hifairlady** [comment]
[](url)

**Comment by actboy168** [comment]
不能调用

**Comment by Kakerate** [comment]
Could you provide some instructions for converting >1.28 Memory Hack to 1.28+ Memory Hack?

Thanks

**Comment by luciouskami** [comment]
Only few changes between 1.27 and 1.28.Dump the .text section of game.dll(1.27 and 1.28) then disasm it compare the difference.Reverse engineering by ypurself  plz. @Kakerate

**Comment by Kakerate** [comment]
I'm talking about the new way of calling the functions, through UnitId. Do you just need to import the files to map mpq and provide the dummy functions? Thats it?
