### ISSUE TITLE
真心求助魔兽地图BUG

### ISSUE THREAD

**Issue by BJL6666** [actboy168/YDWE#119]
这个bug在2017年上半年出现的  出现的过程是我正在测试我做的地图 突然地图弹出 黑色背景的代码 的YDWE.worldEdit 我似乎每次测试地图都弹出 后面不小心点到了 然后按到了键盘上的键 突然地图就测试不聊了 复制地图的地形 以及 文件.j 编程 重做依旧测试不了

**Comment by BJL6666** [comment]
图片不知道怎么上传 找不到上传图片的按键

**Comment by BJL6666** [comment]
我把图片上传百度网盘了 链接https://pan.baidu.com/s/1smlPEjF 希望 大佬帮忙 处理 原本已经破灭的希望在无意中看到了YDWE的BUG解决平台

**Comment by actboy168** [comment]
地图发来看看

**Comment by BJL6666** [comment]
那我把地图传到 百度网盘去 链接: https://pan.baidu.com/s/1kXgS1MZ 密码: 5wiq

**Comment by actboy168** [comment]
你的地图使用了第三方的UI，你可以尝试去掉它，再试试。否则我无法帮你

**Comment by BJL6666** [comment]
如何去掉 ？ 把含有 另外的UI 的触发先删掉？

**Comment by actboy168** [comment]
对，把第三方的UI删掉。你用1.32的话，你用了第三方UI第一次打开的时候会提示你有未知UI，根据提示重启之后，被用红色标记出来的UI就是第三方UI。

**Comment by BJL6666** [comment]
好的 前几天没有时间在线

**Comment by BJL6666** [comment]
如果把他禁用了 你可以打开吗？

**Comment by BJL6666** [comment]
可是我好像没有用第3方的UI 里面虽然有 触发好像没用到 找了一边不清楚 如何全部找出来 ？ 用新版本的WE？

**Comment by BJL6666** [comment]
我用1.31打开后提示 没有 该地图XXX数据还是什么鬼 应该是第三的UI 后面就崩了 WE 打不开 我已经删了我找出来用的第3方UI

**Comment by BJL6666** [comment]
有没有方便的方法

**Comment by actboy168** [comment]
你应该好好看我说的话，这是我们可以交流下去的基础

**Comment by BJL6666** [comment]
我找不到1.32正式版的下载 所以只找到了1.31 是不是用测试版本？

**Comment by actboy168** [comment]
1.32.1 ,可以在http://ydwe.net/download.html下到

**Comment by BJL6666** [comment]
我已经把所有第3方UI 禁掉了 可以开启测试但是还是会弹出 那个黑色背景的程序 要不要我把 禁用的触发删掉 你才能打开 我是想先禁用后在用 1.32的重新做一遍

**Comment by actboy168** [comment]
弹是正常的，因为你地图本身有问题。提示也是中文的，自己想办法改下就好

**Comment by BJL6666** [comment]
提示的中文是超过了字节码限制什么意思

**Comment by BJL6666** [comment]
我已经将第3方UI 改成YDWE的了 重新测试后 虽然可以打开但是 里面的触发都不生效 技能没有技能触发的效果 待会我把地图上次

**Comment by BJL6666** [comment]
我已经将第3方UI 改成YDWE的了 重新测试后 虽然可以打开但是 里面的触发都不生效 技能没有技能触发的效果 待会我把地图上传

**Comment by BJL6666** [comment]
还有 我用YDWE1.32测试版本打开后 保存 他就提示一个对话框 编织器刚刚帮你修改了物体数据 是什么意思

**Comment by BJL6666** [comment]
我用 YDWE具有的触发改了 替换的第3方UI的触发 YDWE1.32可以测试 但是 触发全部没有效果 如果我用我原来的具有第3方UI的 YDWE打开测试后 会崩溃是怎么回事怎么解决 我把地图上传到百度云了链接: https://pan.baidu.com/s/1nxkm2r3 密码: b6rw

**Comment by BJL6666** [comment]
还有一个问题 用YDWE的自带万能属性系统 将地图加密后好像不生效了

**Comment by actboy168** [comment]
你用了别的UI出的问题，你应该去找那个UI的作者，而不是我。

**Comment by BJL6666** [comment]
那我都把UI删掉了 测试的时候 所有的触发都没有触发

**Comment by BJL6666** [comment]
谢谢你之前帮助我 我自己找到了问题源头了 全局变量赋值太大 导致函数无法运行
