### ISSUE TITLE
YDWE有支持1.29的计划吗？

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#120]
果然这个版本和舅舅党之前说的一样把暴雪以前为了更新方便而开发的storm.dll和game.dll 全编译到exe里面了，也不知道暴雪在想点什么。
  其实还是希望YDWE能支持一下1.29的，好歹这次有了点bug未知的实质性更新，不如就支持一下吧。

**Comment by luciouskami** [comment]
瞄了一下，似乎添加jass函数的方法未变，这次的测试版本确实增加了新的jass函数，不过这种行为已经破坏了向下兼容性，并且我不知道这种类似于“静态编译”的方法的意义在哪里，是不是代表1.29以后暴雪不再更新所以才把原本的升级机制完全改变了？看不懂，看不懂。

**Comment by actboy168** [comment]
没有。
首先1.29的变化，影响的是几乎所有的war3工具链，ydwe只是一个处于最下游的工具。ydwe对1.29的支持必然是最迟的那一个，虽然我目前看不到任何可能性。
其次与其考虑YDWE对魔兽的支持，不如考虑YDWE对平台的支持。对于11平台，我觉得他们不会升级1.29；对于网易平台，即使升级1.29也会保留低版本的支持，所以并无影响。

**Comment by luciouskami** [comment]
看暴雪接下来的动作吧。
