### ISSUE TITLE
我用1.31.8自动生产阴影功能就会无响应，在1.28九州城

### ISSUE THREAD

**Issue by sminad** [actboy168/YDWE#124]
之前用1.28自动生成阴影就不会这样，现在换了1.31.8一点自动生成阴影就无响应然后自动关闭了，地图纯地形无触发装饰物1W3，可生产阴影在30%，480X480地形，大量隆起地形，由于后期开发必须在1.31.8这个版本是操作，这样导致后续版本更新的话就无法生成阴影了。。这个功能对我很重要，这是我在贴吧的帖子https://tieba.baidu.com/p/5628028677
麻烦大佬百忙之中能看一下我这个情况，至少能给我一些有用的建议也好，希望尽早就绝这个问题。
PS：刚才问了下别人的地图用1.31.8生成阴影功能，5000多装饰物，无隆起，10分钟左右生成完毕，我的可能比较大，但在1,28版本也就速度慢一点，用1.31.8我生成了2个晚上编辑器都是无响应状态。。。我魔兽版本1.27

**Comment by actboy168** [comment]
我认为和YDWE的版本无关。YDWE本身并没有对阴影计算做任何处理，而WE的阴影计算本身就有很多问题。你的问题可能只是正好触发了某个BUG，而之前没有。

**Comment by luciouskami** [comment]
没事不要计算阴影，各种迷
