### ISSUE TITLE
触发器和变量消失的问题

### ISSUE THREAD

**Issue by Clearave** [actboy168/YDWE#137]
用“YDWE里打开地图，另存为，将地图文件名改为’.w3x’，保存即可生成为Lni格式地图。”的方法保存地图，为什么第二次打开触发器和变量都没有了？只剩一个YDWE的简介。
我打开catalog.lml和variable.lml里面显示是有的

**Comment by Clearave** [comment]
![image](https://user-images.githubusercontent.com/23792118/43687856-f2dea05a-990f-11e8-83f7-62a8d63b7cba.png)
![image](https://user-images.githubusercontent.com/23792118/43687868-1644e9e6-9910-11e8-9f4e-c0f7247c9f7c.png)

**Comment by sumneko** [comment]
请把lni地图发来看看

**Comment by Clearave** [comment]
我另存为这个bug就消失了，使用正常。不过原来那个还是有bug，不知道为什么，有bug这个我是先保存成普通的w3x 再用 w3x2lni_zhCN_v2.4.2 版本的转换器 转的lni，它警告说我没有没有触发器（那时候还没写），我怀疑是不是你们在这种情况下加了一套代码就是覆盖了一切触发器而生成一个YDWE的简介在触发器里面。所以我怀疑是转化器的bug。
[w3xMap002.zip](https://github.com/actboy168/YDWE/files/2260499/w3xMap002.zip)

**Comment by sumneko** [comment]
你可以先通过删除 `map/war3map.wtg` 与 `map/war3map.wct` 这2个文件来临时回避这个问题

**Comment by actboy168** [comment]
已修复
