### ISSUE TITLE
未知乱码

### ISSUE THREAD

**Issue by masakitenchi** [actboy168/YDWE#139]
![image](https://user-images.githubusercontent.com/11086210/43831310-a76363a0-9b3e-11e8-961c-efb8b3421792.png)
虽然本身是日文系统但是已经转成了中文而且Unicode的设置也是中文（中国）但是还是出现这种情况，不知道是魔兽本身的问题还是编辑器的问题

**Comment by actboy168** [comment]
装虚拟机吧

**Comment by diaoseo** [comment]
> 装虚拟机吧

新版不是需要DX12的支持？虚拟机根本不支持这货

**Comment by actboy168** [comment]
dx8 就行
