### ISSUE TITLE
建议增加技能按名字搜索功能

### ISSUE THREAD

**Issue by sotr2333** [actboy168/YDWE#143]
技能很多，查找起来一直很麻烦
建议在图中的框内增加一个搜索框，当然 不是全词匹配的

![screenshot](https://i.imgur.com/PEGkqu7.png)

**Comment by actboy168** [comment]
技能名本身按拼音排序，所以我认为并不需要搜索。

**Comment by cakoyo** [comment]
虽然是拼音排序，但是仍然很难查找

**Comment by cakoyo** [comment]
另外，魔法效果自定义和默认的会混在一起，不知道能否单独分类自定义的魔法效果

**Comment by actboy168** [comment]
对于不存在UI我无法生造一个出来。

但我给列表加了一个可以用键盘快速定位一个项的功能，这和资源管理器类似。例如你按H，就会定位到第一个拼音以H开头的项，再按一次会定位在第二个，依此类推。

**Comment by luciouskami** [comment]
便民功能，资瓷、
