### ISSUE TITLE
设置字体时出现config程序崩溃的情况.旧版本没这个情况

### ISSUE THREAD

**Issue by PhoenixZeng** [actboy168/YDWE#148]
程序版本是1.32.11

**Comment by PhoenixZeng** [comment]
直接修改EverConfig文件 会导致ydConfig文件打开崩溃
修改内容为添加
[Font]
FontEnable = 1
FontName = 宋体WE //此为自己做的字体 在yd旧版本使用多年
FontSize = 9

**Comment by actboy168** [comment]
因为你没改对

**Comment by PhoenixZeng** [comment]
我是直接采用gui界面修改的.打上勾 选个字体选个大小点确定 这个流程还有对错吗? 在选字体的时候就崩溃了
崩溃之后我才尝试的修改everconfig文件.
如果没改对 请问怎么才算正确的做法

**Comment by actboy168** [comment]
你之前说“直接修改配置文件”，现在说“通过GUI修改”。你不提供准确的信息，我是不可能猜出你遇到了什么问题的

**Comment by PhoenixZeng** [comment]
第一次:我第一次采用gui修改的 在字体下拉菜单中点击字体 然后config.exe崩溃了
第二次:之后我尝试直接修改配置文件 修改之后打开config.exe就崩溃
这是两个行为我都测试过了. 这是两个独立的事件
