### ISSUE TITLE
YDWE编辑器几个建议和问题。

### ISSUE THREAD

**Issue by yyy136** [actboy168/YDWE#153]
1.功能调整：设置伤害值[JAPI]为负数时会恢复生命值，这个可以调整下吗。

2.功能调整：[JAPI]特效改变 大小 旋转 这些不能用在改变附加身上的特效，比如origin，chest等等。

3.建议添加：魔兽移动速度上限只有522，模拟也不能完美达到真正的目的，这个有没JAPI突破522速度。

4.建议添加：有没JAPI获取单位的原始模型大小。

**Comment by actboy168** [comment]
你提的这几个都是做不到的

**Comment by yyy136** [comment]
>           你提的这几个都是做不到的

噢。

**Comment by yyy136** [comment]
>           你提的这几个都是做不到的

还有之前我问的问题，我怎么上传我地图给你看下，QQ 还是邮箱。

**Comment by yyy136** [comment]
>           邮箱

你邮箱多少或者加我QQ240167079也可以。
