### ISSUE TITLE
lua预处理为何会删除对象

### ISSUE THREAD

**Issue by PhoenixZeng** [actboy168/YDWE#156]
操作如下
1采用 预处理生成一个对象
2在ydwe物编中复制 `生成的对象` 保存 
3 复制产生的对象会被删除

另外: 提问预处理阶段的StringHash函数现在怎么调用

**Comment by PhoenixZeng** [comment]
版本是1.32.11

**Comment by sumneko** [comment]
默认情况下，物编生成出来的对象是依赖生成代码的，因此你复制出来的对象由于没有对应生成代码而被删除。你可以在生成对象时使用 `permanent` 方法来使对象永久存在，具体可以参考演示图。

**Comment by sumneko** [comment]
就你这个需求而言，幻象马甲的属性应该与原单位同步，但原单位的属性由生成代码决定，无法影响到你复制出来的单位。因此你的幻象马甲也应该由代码生成。

**Comment by PhoenixZeng** [comment]
有道理 . 
能告诉我 预处理阶段的StringHash函数现在怎么调用吗? 直接用会提示没有这个函数 是名字变了还是需要require谁?

**Comment by sumneko** [comment]
我专门测了一下，`StringHash` 是有效的。

**Comment by PhoenixZeng** [comment]
感谢
