### ISSUE TITLE
Use stormlib compact when saving map

### ISSUE THREAD

**Issue by Frotty** [actboy168/YDWE#158]
Currently YDWE creates map mpqs with empty non addressed blocks.
Run stormlib's `compact` to fix this.

**Comment by actboy168** [comment]
Will this be a problem? As far as I know, the official map of war3 also has files that aren't in the listfile.

**Comment by Frotty** [comment]
> Will this be a problem?

It has been a problem several times. YDWE outputs maps with different blocksize and fragmentation from the vanilla WE, thus the maps didn't work in wurst. We have worked around this, but it would be an easy fix on your side. Also these are gaps in the mpq, not real files.

This is the command I mean:
http://www.zezula.net/en/mpq/stormlib/sfilecompactarchive.html
For normal map sizes this process takes under a second for me and would ensure compatibility with other tools.

**Comment by actboy168** [comment]
OK, I have added SFileCompactArchive.

**Comment by Frotty** [comment]
👍
