### ISSUE TITLE
[Bug反馈] 最新版本1.32.11 编译完成打不开ydweconfig.exe

### ISSUE THREAD

**Issue by richardgist** [actboy168/YDWE#159]

**Comment by richardgist** [comment]
![image](https://user-images.githubusercontent.com/7608213/49202695-6eaf3480-f3e0-11e8-8e18-3b71d28b34b2.png)

**Comment by actboy168** [comment]
Already fixed in bb7d323c33aaa48ffafcb3c0227abd0c537ffb9b.
