### ISSUE TITLE
遇到一个崩溃

### ISSUE THREAD

**Issue by w4454962** [actboy168/YDWE#162]
1.32.12的ydwe + 1.24e版本的魔兽 
![image](https://user-images.githubusercontent.com/24670862/50890625-804f1780-1435-11e9-9f50-285520d17435.png)

**Comment by actboy168** [comment]
说明你给的handle类型和object类型不匹配，正常的魔兽不应该出现这种情况

**Comment by w4454962** [comment]
OK 应该是魔兽环境有问题
