### ISSUE TITLE
How to remove JAPI protectioin by YDWE to Rebuild a Map?

### ISSUE THREAD

**Issue by 1kaitoukid1** [actboy168/YDWE#168]
I'm a newbie of using YDWE is there any way to remove JAPI by YDWE to rebuild this map?
Thanks for your help.!
Map:
https://drive.google.com/file/d/12S5lbqSD54akhqPgdCPyvxH25U68Tx75/view?usp=sharing
Mix File:
https://drive.google.com/file/d/1QI38LWOO_hmCN_oeRxb5_eVyxQqAUyjQ/view?usp=sharing

**Comment by actboy168** [comment]
No, I won't help anyone crack the map.
