### ISSUE TITLE
关于哈希表的子键生成

### ISSUE THREAD

**Issue by zhongxinghong** [actboy168/YDWE#201]
您好！想了解一下 YDWE 如何为哈希表生成子键 ID

YDWE 每次编译出来的代码对于特定的 local 变量似乎会分配特定的子键 ID，存储在 YDLOCAL 的哈希表里，例如对于 `GetTriggerUnit` 会使用 `0xC303079D` 作为子键 ID
```
call SaveUnitHandle(Hq,GetHandleId(GetTriggeringTrigger())*Io,$C303079D,GetTriggerUnit())
call SaveUnitHandle(Hq,GetHandleId(GetTriggeringTrigger())*Io,$2B0A6845,GetEventDamageSource())
```

我阅读了一下 YDWE 的源代码，仅仅找到 `0xCFDE6C76` 和 `0xECE825E7` 这两个用于计算 YDLOCAL 的父键，对于子键 ID 的生成，找不到对应的代码，这里就想了解一下这些子键 ID 是如何确定出来的。如果解释起来比较麻烦的话，也希望能指明一下大概需要阅读哪几部分的代码，非常感谢！

**Comment by actboy168** [comment]
变量名的StringHash

**Comment by zhongxinghong** [comment]
谢谢！
