### ISSUE TITLE
1.28.1的逆天传参BUG

### ISSUE THREAD

**Issue by syj2010syj** [actboy168/YDWE#39]
![qq 20141225100045](https://cloud.githubusercontent.com/assets/5213431/5551825/367206c6-8c1d-11e4-814f-ab90520d90cd.jpg)
![qq 20141225100111](https://cloud.githubusercontent.com/assets/5213431/5551820/2fabaf18-8c1d-11e4-8ee8-2bef069b1756.jpg)

在第一层计时器的参数中保存"触发单位"后,生成的代码并没有保存触发单位

**Comment by syj2010syj** [comment]
次奥这2个BUG你就不管了?

**Comment by imba97** [comment]
我就是路过一下 - -

**Comment by syj2010syj** [comment]
第一张图的问题已经修正
