### ISSUE TITLE
YDWE1.285导入模型时丢失自定义main.lua文件

### ISSUE THREAD

**Issue by Qimp** [actboy168/YDWE#45]
很奇怪的一个bug：
1.28.5（1.27.6一样）打开地图，导入6666文件夹里面的模型，点测试发现运行不了main.lua，hke解压出来发现丢失main.lua，继续导入模型，继续丢失lua文件。

如果先导入其他模型，再导入6666文件夹里面的模型，则未出现上述情况。
模型与图在百度云盘：http://pan点baidu点com/s/1jGGcNVC

另：一、 lua文件能用luac编译字节码运行吗？
       二、1.28.5保存出来lua图，并不能在11上运行（未多次测试）

**Comment by actboy168** [comment]
1、MPQ有最大文件数限制，你的地图现在是64，而你已经有60个文件了。WE的批量导入有bug，并不会自动修改最大文件数限制。你需要用MPQ修改最大文件数限制，再导入。
2、可以
3、1.28.5和11的环境略有差别，和1.27.6的更接近，具体你需要进行测试
