### ISSUE TITLE
userdata不能自主添加key和value

### ISSUE THREAD

**Issue by Qimp** [actboy168/YDWE#46]
local hero = CreateUnit(...)
hero["m_hp"] = 100   -- 编译过不去

不知能否实现？如果可以的话可以实现面向对象编程，不得不说是一个福音。

我对lua底层实现不熟，但在cocos2dx里面userdata是可以这么使用的，不知是不是lua版本问题，又或是cocos导出的原因？

**Comment by syj2010syj** [comment]
lua不能直接修改userdata,如果你要添加属性需要自己封装

**Comment by actboy168** [comment]
CreateUnit根据你runtime里的设置可能返回number、lightuserdata、userdata，这三个类型在默认情况都不支持 obj['key'] = val 这种方法。
cocos2dx支持，应该是它给每个userdata添加了额外的__index和__newindex方法的原因。我不喜欢cocos2dx的这种做法。如果你需要，你可以给CreateUnit做一个简单的封装，比如这样

```lua
function create_unit()
    return { handle = CreateUnit() }
end
```

**Comment by Qimp** [comment]
-- 单位表
udg_totalUnitList = {}

-- 类
Hero.m_hero = nil
Hero.m_name = "boy168"
Hero.m_age = 18

function Hero.create( unit )
	local instance = table.deepcopy( Hero )
	instance.m_hero = unit
	return instance
end
function Hero:setXXX(...)
	...
end


-- 创建单位
function LuaCreateUnit(...)
	local unit = CreateUnit(...)

	if unit then
		udg_totalUnitList[unit] = unit
		if GetUnitType(unit) == XXX_HERO then
			return Hero.create( unit )
		else
			....
		end
	end

	return nil
end

-- 获取触发单位
function LuaGetTriggerUnit()
	local unit = GetTriggerUnit()
	return udg_totalUnitList[unit]
end

如果要封装是如上这样？那岂不是在需要用到的每个API里面涉及到unit的都得自己封装一次？
工作量ms有点大。。。是否有其它更便捷的方法？感谢两位！

**Comment by actboy168** [comment]
没有。只是一次性的工作，不算很麻烦

**Comment by Qimp** [comment]
感谢~~
