### ISSUE TITLE
能说明一下编译环境吗

### ISSUE THREAD

**Issue by imcloud** [actboy168/YDWE#47]
下载好后直接去点build目录下的编译命令显然是不行的，只会提示我找不到各种东西。。。

**Comment by actboy168** [comment]
需要msvc2013，如果还不行，把你的错误提示贴出来吧

**Comment by luciouskami** [comment]
除了clone ydwe项目还要clone boost库和python，放到相应的位置才能编译。貌似除了版本号以外别的都没什么问题。
