### ISSUE TITLE
关于std::generic_errno这个函数的问题

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#50]
使用vs2015编译的时候会出现std::generic_errno不是std的成员，查了一下资料好像也没结果，请问下这个问题应该怎么解决

**Comment by aerisnju** [comment]
https://msdn.microsoft.com/en-us/library/ee372175.aspx

没包含头文件？

**Comment by luciouskami** [comment]
“generic_errno”这个成员函数是在<system_error>这个头文件里，有包含，但是依然显示找不到符号。`#include <base/config.h>
#include <exception>
#include <system_error>`

**Comment by actboy168** [comment]
谢谢
