### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#51]
环境 msvc 2015
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2694	“const char *base::win::windows_category::name(void) const”: 重写虚函数的限制性异常规范比基类虚成员函数“const char *std::error_category::name(void) noexcept const”少	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\win\windows_category.h	10	
错误	C2694	“const char *base::win::windows_category::name(void) const”: 重写虚函数的限制性异常规范比基类虚成员函数“const char *std::error_category::name(void) noexcept const”少	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\win\windows_category.h	10	
错误	C2694	“std::error_condition base::win::windows_category::default_error_condition(int) const”: 重写虚函数的限制性异常规范比基类虚成员函数“std::error_condition std::error_category::default_error_condition(int) noexcept const”少	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\win\windows_category.h	12	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
错误	C2059	语法错误:“(”	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\hook\fp_call.h	45	
警告	C4275	非 dll 接口 class“std::exception”用作 dll 接口 class“base::exception”的基	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\exception\exception.h	11	
错误	C2694	“std::error_condition base::win::windows_category::default_error_condition(int) const”: 重写虚函数的限制性异常规范比基类虚成员函数“std::error_condition std::error_category::default_error_condition(int) noexcept const”少	ydbase	d:\github\ydwe2\development\editor\core\ydbase\base\win\windows_category.h	12	

https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=ZH-CN&k=k(C2059);&rd=true
https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=ZH-CN&k=k(C2694);&rd=true

**Comment by actboy168** [comment]
目前没计划支持msvc2015，你可以自己改。或者提pr，保证兼容msvc2010和msvc2013就行。

**Comment by luciouskami** [comment]
太烦不升了，反正也没什么卵用。

**Comment by tc-imba** [comment]
我上次用2015编译成功了
弄了半天 需要修改一些东西
有空发个pr
