### ISSUE TITLE
关闭ydwe后出现崩溃

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#52]
```asm
73C7238E >/$  55            push ebp
73C7238F  |.  8BEC          mov ebp,esp
73C72391  |.  83E4 F8       and esp,0xFFFFFFF8
73C72394  |.  6A FF         push -0x1
73C72396  |.  68 806EC773   push log.73C76E80
73C7239B  |.  64:A1 0000000>mov eax,dword ptr fs:[0]    ; SEH链指针
73C723A1  |.  50            push eax
73C723A2  |.  81EC A0000000 sub esp,0xA0
73C723A8  |.  A1 00C0C773   mov eax,dword ptr ds:[0x73C7C000]
73C723AD  |.  33C4          xor eax,esp
73C723AF  |.  898424 980000>mov dword ptr ss:[esp+0x98],eax
73C723B6  |.  53            push ebx
73C723B7  |.  56            push esi
73C723B8  |.  57            push edi
73C723B9  |.  A1 00C0C773   mov eax,dword ptr ds:[0x73C7C000]
73C723BE  |.  33C4          xor eax,esp
73C723C0  |.  50            push eax
73C723C1  |.  8D8424 B00000>lea eax,dword ptr ss:[esp+0xB0]
73C723C8  |.  64:A3 0000000>mov dword ptr fs:[0],eax
73C723CE  |.  8BF1          mov esi,ecx      ;  ecx=this指针
73C723D0  |.  8B0E          mov ecx,dword ptr ds:[esi]
73C723D2  |.  33DB          xor ebx,ebx
73C723D4  |.  8B7D 08       mov edi,[arg.1]
73C723D7  |.  3999 84000000 cmp dword ptr ds:[ecx+0x84],ebx
73C723DD  |.  74 1F         je short log.73C723FE
73C723DF  |.  8B57 10       mov edx,dword ptr ds:[edi+0x10]
73C723E2  |.  33C0          xor eax,eax
73C723E4  |.  0391 D8000000 add edx,dword ptr ds:[ecx+0xD8]
73C723EA  |.  1381 DC000000 adc eax,dword ptr ds:[ecx+0xDC]
73C723F0  |.  3BC3          cmp eax,ebx
73C723F2  |.  77 16         ja short log.73C7240A
73C723F4  |.  72 08         jb short log.73C723FE
73C723F6  |.  81FA 00000800 cmp edx,0x80000
73C723FC  |.  73 0C         jnb short log.73C7240A
73C723FE  |>  8B41 30       mov eax,dword ptr ds:[ecx+0x30]
73C72401  |.  8B40 04       mov eax,dword ptr ds:[eax+0x4]    ; crash,eax=9DAA3800 
73C72404  |.  395C08 3C     cmp dword ptr ds:[eax+ecx+0x3C],ebx
73C72408  |.  74 07         je short log.73C72411
73C7240A  |>  8BCE          mov ecx,esi
73C7240C  |.  E8 F9010000   call log.?rotate_file@backend@logging@@Q>
73C72411  |>  8B06          mov eax,dword ptr ds:[esi]
```
EAX 9DAA3800
ECX 009CFFFF
EDX 00AE50B8
EBX 00000000
ESP 0018FB3C
EBP 0018FBF8
ESI 009C7798
EDI 0018FC18
EIP 73C72401 log.73C72401
LastErr ERROR_CLASS_DOES_NOT_EXIST (00000583)

这个问题在我的机器上可以得到完整的复现，打开YDWE，用OD附加wordeditydwe.exe，在log.dll+2401处下断，恢复主线程，关闭we。此时会在断点处断下，一直F9到所有模块卸载即栈中日志文件输出有” Main program exit”时。
在当前call入口处下断一直跟到log.dll+2401中间就会发现[ecx+30]处存放的地址明显非法，之后把这里的值给eax以后再对[eax+4]访问，一个非法的地址肯定会引发访问违规，具体崩溃原因（类里面访问的问题？）由于水平有限无法发现，希望我的反馈对解决问题有所帮助。

**Comment by luciouskami** [comment]
``asm
68A035A3  /$  55            push ebp
68A035A4  |.  8BEC          mov ebp,esp
68A035A6  |.  83E4 F8       and esp,0xFFFFFFF8
68A035A9  |.  6A FF         push -0x1
68A035AB  |.  68 E16FA068   push log.68A06FE1
68A035B0  |.  64:A1 0000000>mov eax,dword ptr fs:[0]
68A035B6  |.  50            push eax
68A035B7  |.  83EC 28       sub esp,0x28
68A035BA  |.  A1 00C0A068   mov eax,dword ptr ds:[0x68A0C000]
68A035BF  |.  33C4          xor eax,esp
68A035C1  |.  894424 20     mov dword ptr ss:[esp+0x20],eax
68A035C5  |.  53            push ebx
68A035C6  |.  56            push esi
68A035C7  |.  57            push edi
68A035C8  |.  A1 00C0A068   mov eax,dword ptr ds:[0x68A0C000]
68A035CD  |.  33C4          xor eax,esp
68A035CF  |.  50            push eax
68A035D0  |.  8D4424 38     lea eax,dword ptr ss:[esp+0x38]
68A035D4  |.  64:A3 0000000>mov dword ptr fs:[0],eax
68A035DA  |.  8BF1          mov esi,ecx
68A035DC  |.  837E 40 00    cmp dword ptr ds:[esi+0x40],0x0
68A035E0  |.  0F84 EE000000 je log.68A036D4
68A035E6  |.  807E 45 00    cmp byte ptr ds:[esi+0x45],0x0
68A035EA  |.  0F84 E4000000 je log.68A036D4
68A035F0  |.  8B06          mov eax,dword ptr ds:[esi]
68A035F2  |.  6A FF         push -0x1
68A035F4  |.  FF50 0C       call dword ptr ds:[eax+0xC]              ;  crash
68A035F7  |.  83F8 FF       cmp eax,-0x1
68A035FA  |.  75 07         jnz short log.68A03603
68A035FC  |.  32C0          xor al,al
68A035FE  |.  E9 D3000000   jmp log.68A036D6
68A03603  |>  51            push ecx
68A03604  |.  51            push ecx
68A03605  |.  8D4C24 20     lea ecx,dword ptr ss:[esp+0x20]
68A03609  |.  E8 61FDFFFF   call log.68A0336F
```
还有log+35f4这个地方也会崩溃。具体就是log+2401上面那个跳转跳不跳了。跳就是这里不跳就是上面。

**Comment by actboy168** [comment]
看起来是解决了
