### ISSUE TITLE
1.30.3测试版的两个问题

### ISSUE THREAD

**Issue by 1143910315** [actboy168/YDWE#58]
一、我做的一个图，1.29.4可以保存，在1.30.2及1.30.3保存会提示不能读取文件。解决方法竟然是删除掉一些触发？此问题会不断在我写了新的触发后出现，而我每次都要删除以前的触发来进行保存。
二、我的MPQMaster无法完整解压出所有文件，即，用MPQMaster打开一个地图，选择全部解压，再用MPQMaster新建一个地图，把解压的文件导进去。1.30.3的YDWE总会丢失一些数据，比如导入的模型

**Comment by actboy168** [comment]
1.上地图
2.没重建导入表？

**Comment by 1143910315** [comment]
怎么上地图

**Comment by 1143910315** [comment]
把压缩包里的2.w3x的触发复制到1.w3x，保存就会出问题

**Comment by actboy168** [comment]
actboy168@gmail.com

**Comment by 1143910315** [comment]
我传给你的是用1.29保存的，用MPQMaster可以读取所有文件，换1.30保存就会损失非常多文件

**Comment by actboy168** [comment]
jasshelper是用sfmpq来操作mpq，所以会有一些奇怪的问题。你可以在选项里勾上“jasshelper兼容模式”，这样ydwe会先用stormlib导出文件再给jasshelper编译，这样可以避免sfmpq的问题

**Comment by 1143910315** [comment]
然而MPQMaster还是无法读取所有文件

**Comment by actboy168** [comment]
这是MPQMaster的问题

**Comment by 1143910315** [comment]
1.29.4不会有这个问题，而且我用其他工具，照样读取不出来全部

**Comment by 1143910315** [comment]
对了，你的boost用的什么版本的，我安装boost_1_62_0却不像网上给出的那样子。为了你这个开源项目。。。我VS2012都下载了。。。

**Comment by actboy168** [comment]
1. 魔兽读起来没问题就行，其他工具如果读不了魔兽可以读的mpq，说明它自己有问题
2. boost 用这个 https://github.com/actboy168/Boost

**Comment by 1143910315** [comment]
额，你的boost是怎么做到一个大写B一个小写b的文件夹的。。。

**Comment by actboy168** [comment]
github的bug...
