### ISSUE TITLE
请问YDWE能设置不读取war3根目录下的*.mix *.mix* *.flt *.asi *.m3d文件吗？

### ISSUE THREAD

**Issue by dianso** [actboy168/YDWE#63]
平时做了很多小插件，放到魔兽目录下，魔兽启动自动注入，很方便。

但是每次YDWE启动也会自动注入这些文件，导致YD打不开，我都的把我的小插件全复制到其他文件夹才能使用YD，希望可以不要被这些dll文件注入。

**Comment by actboy168** [comment]
看[ydwe_on_startup.lua#L223](https://github.com/actboy168/YDWE/blob/master/Development/Component/share/script/ydwe_on_startup.lua#L223)
event.EVENT_MSS_LOAD可以控制是否加在这些dll

不过我认为更好的做法是，你的dll应该检测当前进程是war3还是we，来决定是否启用你的功能

**Comment by luciouskami** [comment]
你可以在ThreadAttach里面判断当前进程是不是war3啊，因为编辑器默认也是加载这些后缀的文件。

**Comment by dianso** [comment]
感谢，已解决
