### ISSUE TITLE
I see nothing, this editor only for CHINA ??

### ISSUE THREAD

**Issue by Karaulov** [actboy168/YDWE#64]
![tuf6cs3 1](https://cloud.githubusercontent.com/assets/6445336/20129047/f4999d88-a65d-11e6-8f8d-8c28cb607031.png)

Is possible to change language to english ?

**Comment by actboy168** [comment]
You can  replace the `mpq/ydwe/ui/WorldEditStrings.txt`  file. It can solve part of the problem. 
You can find  `WorldEditStrings.txt` from your  war3.
