### ISSUE TITLE
特效japi ui小问题

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#69]
特使效果-移动[japi]
特使效果-移动[japi]
是不是可用改为：
特使效果-移动 到坐标[japi]
特使效果-移动 到点[japi]

不然两个一样，傻傻分不清。

**Comment by actboy168** [comment]
嗯，UI还没做好。等新的UI管理器

**Comment by luciouskami** [comment]
gui？还是直接写代码？

**Comment by actboy168** [comment]
2ff1d21251459ab2511699b1fff14bba57064f05

**Comment by luciouskami** [comment]
了解  窝看看
