### ISSUE TITLE
1.30.6 创建空图保存后无法正常使用地图优化精灵进行优化

### ISSUE THREAD

**Issue by LazyKnightX** [actboy168/YDWE#71]
原因：
war3mapMap.blp在保存时被修改，导致数据异常，进而导致无法被优化。

重现步骤：
* 创建任意空图
* 删除触发器所有目录
* 自定义脚本区输入注释”//“（不含引号），用于保存时被判定为w3x格式
* 物编中将人族农民的第三个技能删除
* 保存

完成这些步骤后blp已成为被损坏的blp，使用【地图优化精灵 1.87 - U9四周年纪念版】进行优化，无法被自动判定为“高压缩重建地图”，该症状即表示地图内部文件已异常。

注：
* 正常空图优化后尺寸：~95KB
* 异常空图优化后尺寸：~170KB

**Comment by actboy168** [comment]
请用wc3mapmax++,ydwe不可能对停止更新几年的优化器做兼容
