### ISSUE TITLE
建议YDWE把开源协议换成GPL

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#72]
Apache这么宽松的协议也有人不遵守，很服。干脆换个GPL好了。

**Comment by actboy168** [comment]
不遵守的人换什么都不会遵守的

**Comment by luciouskami** [comment]
完全拿了ydwe war3操作部分的框架，dll里面连符号也不改一下（偷东西都这么明目张胆），而且连放一份Apache协议和修改说明这么简单的事情都没做，把原作者的付出就这样抛开，我看着挺不舒服的。

**Comment by actboy168** [comment]
淡定，牛逼的永远是人而不是代码

**Comment by luciouskami** [comment]
嗯，他们也不可能偷到人脑子里知识。我就是看不惯这种做法。
