### ISSUE TITLE
YD的JAPI框架不考虑独立封装么

### ISSUE THREAD

**Issue by LazyKnightX** [actboy168/YDWE#73]
今晚研究了YD的JAPI框架，拓展性和适用性都很广泛，并且长期运用也保证了稳定性，轻松封装一下就会是个很强大的能够供开发者拓展的框架，是否有打算做封装呢？

**Comment by actboy168** [comment]
独立封装是什么

**Comment by LazyKnightX** [comment]
从ydwe中提取出来，将编译环境独立发布，允许用户在没有ydwe全部源码的情况下撰写dll并编译。我看了一下依赖项只有两个，能提取出来做成独立框架而非目前这样嵌入ydwe的话能够极大程度上推广japi，并且可参与性很强。目前的功能封装做得非常好，其实已经让japi的编写门槛降低很多了，能提取出来的话能够让很多没有破解基础和汇编基础的人参与，只需要专注实现功能就行了

**Comment by actboy168** [comment]
japi需要多端支持，你自己写一个毫无意义。所以我不建议任何人来实现japi。

**Comment by LazyKnightX** [comment]
好吧，不过介意我封一个独立出来么？仍然基于开源发布

**Comment by actboy168** [comment]
在遵守LICENSE的前提下，代码随意使用

**Comment by LazyKnightX** [comment]
感谢

**Comment by w4454962** [comment]
现在用return bug似乎已经解决多端问题了。
