### ISSUE TITLE
关于ui的问题

### ISSUE THREAD

**Issue by tc-imba** [actboy168/YDWE#74]
正在写一支持原版we和ydwe各版本的ui编辑器&包管理器（类似npm）
原版we和ydwe早期版本的ui的结构我非常了解

上版本和新版ui，ydwe中开始分目录储存了，但在ydwe和ydtrigger中的[TriggerCategories]下分别有
TC_YDLC=变量[YDWE],ReplaceableTextures\WorldEditUI\Editor-ScriptVariable.blp
TC_YDLC=变量[YDWE],ReplaceableTextures\WorldEditUI\Editor-ScriptVariable.blp,1
（名称重复了）
懒得看源码了，请问现在ydwe的解析对这样的重定义是怎么处理的呢？

ps. 新版ui的格式稳定后再提供支持吧

**Comment by actboy168** [comment]
同名的值，优先级高的UI包生效
