### ISSUE TITLE
技能消失

### ISSUE THREAD

**Issue by 1143910315** [actboy168/YDWE#80]
目前发现1.313少了蝗虫等等技能。

**Comment by 1143910315** [comment]
别问我为什么close了又open，因为我本来写的1.31.2，隔了一下，我发现新版本出了，close了，结果1.31.3还是没蝗虫。。。

**Comment by 1143910315** [comment]
随便反馈一个疑似bug，选取单位组指定条件，如果条件and的太长，会产生乱码

**Comment by actboy168** [comment]
> 顺便反馈一个疑似bug，选取单位组指定条件，如果条件and的太长，会产生乱码

做个演示吧

**Comment by 1143910315** [comment]
奥，发现没说明白，，，是在触发编辑器显示的时候截断了长度，刚好截在中文上就乱码了

**Comment by actboy168** [comment]
这个没有办法，WE对中文的支持几乎为零

**Comment by 1143910315** [comment]
那就解决一下物编缺少技能的问题吧。。。没有蝗虫瘆得慌，技能的马甲都不好做了。
