### ISSUE TITLE
逆天计时器里的逆天局部变量类型乱用不报错

### ISSUE THREAD

**Issue by 1143910315** [actboy168/YDWE#82]
Hi~ o(*￣▽￣*)ブ
又是我。
在触发器里定义整数逆天局部变量然后紧接着当做实数使用报错，
但是在逆天计时器里，不管把a用在任何类型上，都不会报错，而是可以测试。
这是个悲伤的故事，我把两单位之间的距离当做两点之间的距离来用。测试了好多遍，不知道问题出在这里。/(ㄒoㄒ)/~~

**Comment by actboy168** [comment]
不懂你在说什么，上演示吧

**Comment by 1143910315** [comment]
![c](https://cloud.githubusercontent.com/assets/20817444/22931137/7fc135a0-f2fe-11e6-9122-d3312e2bb732.png)
如果是12KB的图片，就下载了吧

**Comment by actboy168** [comment]
计时器确实没有校验

**Comment by 1143910315** [comment]
我貌似记得以前有的吧。。
