### ISSUE TITLE
建议：代码注入优化

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#86]
目前有部分地图触发器比较多，在注册的时候很容易执行上限导致触发失效，建议在注入的时候能够适当地使用ExecuteFunc()这个函数来注册来规避这个问题。

**Comment by actboy168** [comment]
触发器多到达到执行上限，说明这张图应该需要重构了，比如使用触发器休眠之类的技巧。ExecuteFunc并不能解决问题

**Comment by luciouskami** [comment]
我也是这么想的，ExecuteFunc只是个治标不治本的方法，但是现在很多作者并不会使用触发器休眠，至于精简和重构，在没有人引导的情况下，对于这部分作者来说是一件比较困难的事情。

**Comment by actboy168** [comment]
如果这个都用不了的话，我认为这个作者也驾驭不了如此复杂度(这种规模触发器)的地图

**Comment by luciouskami** [comment]
主要是因为最近提出这个问题的作者有点多，统一让他们用休眠吧，重构看个人了。

**Comment by luciouskami** [comment]
fixed
