### ISSUE TITLE
有些英雄数据对不上

### ISSUE THREAD

**Issue by 1143910315** [actboy168/YDWE#89]
虽然不清楚是什么问题，但确实发生了有些英雄的护甲会莫名高一点或低一点，例如修补匠，进去游戏总比其它英雄低一点护甲（当我修改了其它数值，护甲就是正常的）。
不知道这是魔兽版本不同造成的数据不同，还是YDWE里的数据错了？

**Comment by actboy168** [comment]
你魔兽的版本和编辑器的版本的数据不一样

**Comment by 1143910315** [comment]
=_=那我联机玩，这护甲应该如同局域网的吧，有没有办法说强制设定的？就是说我那些英雄的护甲要统一，怎么让修补匠的护甲不减低一点啊？还是说那个数值的护甲永远不能用了（除了靠技能叠护甲外）？

**Comment by 1143910315** [comment]
=_=还是说，每次玩过平台过都转回1.24？然后再开WE？

**Comment by luciouskami** [comment]
@1143910315 
  现在的平台都会自动载入对应版本的game.dll，编辑器数据设置为1.07就行了。

**Comment by 1143910315** [comment]
@luciouskami 原来如此，谢谢了。也就是在平台玩的时候并不会出现护甲不一致的问题了吧。

**Comment by luciouskami** [comment]
@1143910315 
也不是这么说，我记得暴雪从1.24b以后的升级都没有balance方面的改动了，如果你本地的魔兽版本是1.24b以上的，编辑器数据设置为最新，应该不会出现你所说的情况，但是如果你在11平台玩，平台会自己载入一个mpq文件，里面的slk metatable 应该是修改过的，不知道是不是based on 1.07，所以我建议你还是将地图数据设置为1.07

**Comment by 1143910315** [comment]
@luciouskami 
额，我确认过是1.07，魔兽版本的确是1.24，平台是网易。那这又算什么？？
========================================================
新建地图，死亡骑士编辑器为1护甲，测试为2护甲，版本转换器显示1.24.4.6387（进入魔兽也是这个版本号）

**Comment by luciouskami** [comment]
@1143910315 
 如果是网易的话，我需要看一下网易做了点什么，网易的魔兽版本是1.27，进入游戏以后版本号应该会变化的

**Comment by 1143910315** [comment]
@luciouskami 那就麻烦你了，补充一下，我是局域网测试，由于蝗虫等技能丢失，我有从github上直接复制fix #80 的文件覆盖YDWE1.31.1测试版。
我水平实在不够，现在在做YDWE颜色插件都显得有些吃力。（我有点嫌弃现在的颜色插件，没有“热键色”这些常用色，还要.net支持，虽然我装了vs2017的不担心.net）

**Comment by luciouskami** [comment]
@1143910315 
  用什么语言开发颜色插件？ 如果是.net恐怕还是会引起crash，当然也有可能是代码问题。顺便你把要测试的演示图也传一份上来吧。

**Comment by 1143910315** [comment]
![b](https://cloud.githubusercontent.com/assets/20817444/23331792/3e400af4-fba8-11e6-8ff7-7cb29e12f27f.jpg)

1、lua 、 c++ 的win32，然而我是小白，基本都是靠百度才做起来的，其实我更会C#一点，有兴趣可以[点这里](https://github.com/1143910315/YDColorizer)。
2、DOS混合文件已经接触过吧，github连zip格式都不给上传，估计是好压已经不再是通用的zip格式了。

**Comment by 1143910315** [comment]
@luciouskami 
其实我以前（几年前）曾经使用易语言开发过颜色插件，但是就是崩溃率太高了（造成YDWE卡死），其根本原因大概是有些控件不能稳定支持改变父窗口情况，我使用其他控件有崩溃率下降情况。C#可能有些控件被封装过，猜测也可能不能稳定支持改变父窗口，或许改变一下使用的控件，会有好转。
PS：我在想，actboy168的邮箱会不会炸了，如果大神测试完没有结论，要不就请直接联系我吧？QQ号码就是github的ID，明天要去上学，可能会“失联”。

**Comment by luciouskami** [comment]
@1143910315 
=====================================================
测试了一下好像没问题。可能是我没明白你的意思？不如你说明一下差异在哪里。
https://mega.nz/#!JdVlkLzJ!0RMv9qRSPwyUSdZHID6wTdrN-e5X9mw9Mw5ojuiqajY

**Comment by 1143910315** [comment]
@actboy168 大神你看看吧，进入地图如果看见一个是1护甲，一个是2护甲，就说明数据对不上（编辑器里这两个英雄都是1护甲），神话大神已经确认了这个问题，但是他说没空，还要麻烦@actboy168 大神你看看吧。神话大神说平台里和局域网都是一样的结果（也就是和编辑器对不上，而且魔兽版本也不低【我的1.24，神话大神是1.27】，数据是1.07的）

**Comment by luciouskami** [comment]
@1143910315 
这个测试方法是有问题的，应该优化成slk以后在测试，这就不变了你可以试试。

**Comment by 1143910315** [comment]
@luciouskami slk优化后，单人游戏测试，问题不变。。。你有时间发这个问题的时候，应该亲测一下。。。
