### ISSUE TITLE
刷兵计时器停不下来了！

### ISSUE THREAD

**Issue by 1143910315** [actboy168/YDWE#90]
不管使用哪种方式，都无法成功停下来=。=

**Comment by w4454962** [comment]
小哥 怎么不问问神奇的海螺呢

**Comment by 1143910315** [comment]
@w4454962 楼上扰民差评，这里是不应该扯淡的地方。
顺便上传一个演示图
![b](https://cloud.githubusercontent.com/assets/20817444/23332438/85b94d4e-fbb4-11e6-8fed-b548df2fd3d6.jpg)
