### ISSUE TITLE
YDWE官方网站打开极慢

### ISSUE THREAD

**Issue by FGFW** [actboy168/YDWE#92]
由于360已经停止了useso.com的服务，导致ydwe官方网站打开极慢。希望能修一下.

**Comment by actboy168** [comment]
已解决，谢谢

**Comment by FGFW** [comment]
fonts.googleapis.com 需要翻墙才能打得开。所以打开官网还是很慢的。

**Comment by luciouskami** [comment]
一般来说对于WordPress的字体加载缓慢导致站点访问缓慢，可以把字体下载到本地，或者使用镜像源解决。

**Comment by FGFW** [comment]
我找到了两个镜像源服务
中科大的https://servers.ustclug.org/2015/09/google-revproxy-add-cache/

极客族 http://cdn.geekzu.org/cached.html

**Comment by actboy168** [comment]
没有被墙，除了个别dns错了
http://www.17ce.com/site/ping/201703_7ef2a3fcc329c540e810b2280263cbcc.html

**Comment by FGFW** [comment]
我这里DNS的解析是正确的。不过确实是访问不了。
可能是不同运营商策略不完全相同，或者其它原因。
没有疑问了。此问题可以关闭了。
