### ISSUE TITLE
技能提示文本会造成歧义

### ISSUE THREAD

**Issue by 1143910315** [actboy168/YDWE#94]
人族的减速，减速效果那一行用的是%，而数据是0.25，可能会误以为是0.25%，我建议将%改成“倍”。
而兽族的狂战士，没有%，而数据的单位与减速技能是一致的。
特别是人族的魔法防御，反弹几率没有%而下面几项都有%，更容易让人误以为数据单位是不一样的

**Comment by actboy168** [comment]
%的用法我认为没问题。%指的是这项数据是乘法叠加而非加法叠加。而概率50即使50%而不是0.5，我相信也很好理解。至于单位的问题，作为一个已经存在十几年的编辑器而言，不宜改变使用习惯。相反地，如果有个别单位是100倍的数据，可以对它进行特别说明。
据此，我认为狂战士的说明是有问题的。
