### ISSUE TITLE
源码有bug疑问

### ISSUE THREAD

**Issue by w4454962** [actboy168/YDWE#95]
我是在去年12月左右的时候下载的源码 在lua引擎里
require 跟老版本不同 不带.lua后缀
print 没有在控制台里显示
玩家等待 这个J函数似乎无效 我是下了有bug的源码了吗？

**Comment by actboy168** [comment]
1.issues是用来解决问题的地方，不是贴吧也不是论坛。不要说一些含糊不清的事情
2.这里只讨论最新的版本，任何历史版本不作考虑

**Comment by w4454962** [comment]
好的 在你发布的 1.31.3测试版 的lua里 TriggerSleepAction 是无效的 即使require "jass.runtime".sleep=true也是无效的 不知最新版里有无修复？

**Comment by actboy168** [comment]
我测试没有问题，不过需要注意的是TriggerSleepAction不是任意上下文都有效，比如在condition内执行的代码就无法使用TriggerSleepAction。

**Comment by w4454962** [comment]
<?import('test.lua')[[
 require 'jass.runtime'.sleep=true
 CJ=require 'jass.common'
 CJ.DisplayTextToPlayer(CJ.Player(0),0,0,'AAAA')
 CJ.TriggerSleepAction(5)
 CJ.DisplayTextToPlayer(CJ.Player(0),0,0,'BBBBB')
]]
?>

同时发送 不知是我写错了吗

**Comment by w4454962** [comment]
<?import('test.lua')[[
 require 'jass.runtime'.sleep=true
 CJ=require 'jass.common'
 CJ.DisplayTextToPlayer(CJ.Player(0),0,0,'AAAA')
 CJ.TriggerSleepAction(5)
 CJ.DisplayTextToPlayer(CJ.Player(0),0,0,'BBBBB')
]]
?>

同时发送 不知是我写错了吗

**Comment by w4454962** [comment]
import('test.lua')[[
 require 'jass.runtime'.sleep=true
 CJ=require 'jass.common'
 CJ.DisplayTextToPlayer(CJ.Player(0),0,0,'AAAA')
 CJ.TriggerSleepAction(5)
 CJ.DisplayTextToPlayer(CJ.Player(0),0,0,'BBBBB')
]]

**Comment by actboy168** [comment]
主线程不能sleep

**Comment by w4454962** [comment]
在协程里？ 还是 可以给个例子吗

**Comment by actboy168** [comment]
```
TriggerAddAction(t, function ()
    TriggerSleepAction(1.)
end)
```

**Comment by w4454962** [comment]
好的谢谢  /尴尬
