### ISSUE TITLE
JassHelper对未初始化的全局变量不报错

### ISSUE THREAD

**Issue by KanoKano2017** [actboy168/YDWE#97]
发现jass全局变量如果不初始化就无法正常运行，但JassHelper对此不报错，可否添加检查未初始化的全局变量功能？

**Comment by w4454962** [comment]
这个好像有提示把  就是使用没初始化的全局变量 会弹出个黑窗口的

**Comment by luciouskami** [comment]
一般YDWE都会自动初始化全局变量，没有初始化的变量一般是局部变量。

**Comment by actboy168** [comment]
理论上无法做到编译时检查使用了未初始化的全局变量。运行时检查，如w4454962所言，已经有了。
