### ISSUE TITLE
@vaxuinha 的问题

### ISSUE THREAD

**Issue by actboy168** [actboy168/YDWE#98]
@vaxuinha 
1. 不要在无关的地方留言。有问题请用issuss
2. 提问就说出你的问题，不要说毫无意义的话

**Comment by vaxuinha** [comment]
对不起，是我第一次来这里

**Comment by vaxuinha** [comment]
所以，我不是来自中国，我想要使用ydwe编辑器，但字母不会出现
http://imgur.com/a/JXD3B
我需要在中文地图上做这个编辑
你可以帮我吗？

**Comment by actboy168** [comment]
编辑中文地图，你需要一个中文的环境。你可以在windows的控制面板里安装中文的语言包，然后把windows的区域改为中文。

**Comment by vaxuinha** [comment]
简体中文包?

**Comment by actboy168** [comment]
没有支持英文的计划
况且你的需求是编辑中文地图，所以无论如何都是需要中文的语言包的。

**Comment by luciouskami** [comment]
@vaxuinha 因为你是要编辑中文地图，那么首先你需要把你的Windows语言改为中文，然后下载一个简体中文版本的魔兽争霸3，这样你就可以使用YDWE了。

**Comment by vaxuinha** [comment]
好
我试图在另一个编辑器打开，我不能因为一些“triggers”，如果我删除，那么我可以在普通编辑器打开？

**Comment by actboy168** [comment]
这取决于你的地图用了多少ydwe的功能。如果很少可能比较容易，如果很多，或许你要几乎删掉整张地图

**Comment by vaxuinha** [comment]
是
你能看到吗？我可以发送触发器的名字
triggers

**Comment by actboy168** [comment]
不明白你的意思

**Comment by vaxuinha** [comment]
如果我发送我的编辑器数据库中没有的''触发器'的名称，如果我发送你打开地图并禁用它们，如果可能，我打开没有yd？
if i send the map for you open in yd , for disable the triggers , for me try to open in my editor , if possible

**Comment by actboy168** [comment]
嗯，你可以发到我的邮箱

**Comment by vaxuinha** [comment]
我有qq，如果你想要的
你的电子邮箱是什么？

**Comment by actboy168** [comment]
我不用qq

actboy168@gmail.com

**Comment by vaxuinha** [comment]
ok
我会发送地图和一个带触发器的照片 triggers 
谢谢^^

**Comment by actboy168** [comment]
看起来这是一张大量使用了ydwe功能的地图，所以没办法通过删除某些函数来让官方WE打开的目的。

**Comment by vaxuinha** [comment]
i understand
不需要删除，但可以禁用它吗？也许工作

**Comment by actboy168** [comment]
禁用也是一样，这个几乎等价于把war3map.wtg删了。所以你可以自己通过mpq工具做到这点

**Comment by vaxuinha** [comment]
谢谢你的尝试
为了让我需要在yd中编辑他，我看不到，你能做到吗？这些信
我有另一个问题，我只能在这个编辑器中编辑他，我不能使用另一个？
In order to make me need to edit him in yd and i can not see , can you do this?
i have another question , i only can edit him in this editor , i can't use another?

**Comment by actboy168** [comment]
是的，所以安装中文包是最好的选择

**Comment by vaxuinha** [comment]
我试过，但没有工作
