### ISSUE TITLE
疑问：jass：：hook能否在游戏开始加载以后起效？

### ISSUE THREAD

**Issue by luciouskami** [actboy168/YDWE#99]
我看到lua引擎中是这么写的
```c++

		bool install(lua_State* L, const jass::func_value* nf, const char* name, int fake_func)
		{
			if (real_func_)
			{
				uninstall();
			}

			L_ = get_mainthread(L);
			nf_ = nf;
			name_ = name;
			fake_func_ = fake_func;

			if (!code_base_)
			{
				code_base_ = create_jmp_code();
				if (!code_base_)
				{
					return false;
				}
			}


		}


```
用了这个方式：
```c++
  return (jass::HOOK_MEMORY_TABLE | jass::HOOK_ONCE_MEMORY_REGISTER) == jass::hook(name_.c_str(), &real_func_, code_base_, jass::HOOK_MEMORY_TABLE | jass::HOOK_ONCE_MEMORY_REGISTER);
```
  11平台和YDWE环境下对game.dll的相关hook发生在创建进程时。
  我尝试在游戏加载的时候进行hook操作，使用同样的代码，经过调试发现虽然jass::async_hook返回成功，但是无实际效果。（测试函数为：DisplayTextToPlayer）后阅读源码发现 无论前两步操作的结果如何,async_hook总是返回成功。
在
```c++
  detail::async_initialize()
```
这个函数中调用了search_register_func()用来搜索“StringCase”这个jass函数的地址，但是我并不清楚它的作用是什么。
所有的hook方式最终都走到了jass::table_hook()这个函数中，看起来是似乎是定位不到jass的哈希表引起的失败？
但是游戏加载前就能成功，而游戏开始加载以后却会失败，对于其中的原因有点疑惑。

**Comment by luciouskami** [comment]
继续阅读了一下源码，table_hook的原理似乎是在jass虚拟机注册函数前修改函数的地址达到hook的效果？所以当游戏开始加载以后代表jass函数已经全部注册完成，不再执行那段流程，所以游戏开始加载以后再进行hook就没有效果？如果是这样的话有没有一种能够在游戏加载以后hookjass函数的方案(除了inlinehook这种非常不优雅的方式以外)？

**Comment by luciouskami** [comment]
经过调试发现之前的猜测有错误，“GetInstance”这个函数好像无时无刻不在被调用，相反的，在“game.dll + 45DCC8”这个地址附近的函数调用比较敏感，当游戏启动的时候被调用，当玩家选择地图的时候被调用（此时附近出现了 jass函数的签名），当地图加载过了三分之二的时候又开始被调用，猜测是响应“地图初始化”这个事件（我测试的地图在地图初始化的时候会创建很多计时器，此时这个地址附近出现了“CreateTimer”这个字符串，故而由此猜测）。
然后并不能理清楚它们之间的关系找出hook失效的原因，求解惑。

**Comment by actboy168** [comment]
我测试没有问题

**Comment by w4454962** [comment]
table_hook 是在地图开始之后 随时可以hook的 我这边也是正常的

**Comment by w4454962** [comment]
对了 我在使用 table_hook之前 调用了func_value.cpp 里的 initialize_mapping 注册了函数地址   也许跟这个有关？

**Comment by w4454962** [comment]
GetInstance(5) 是获取jass虚拟机 很多cj函数都会通过虚拟机进行数据操作 所以无时不刻不被调用的

**Comment by w4454962** [comment]
关于StringCase 猜测是在这个函数之前的内容是 R2S R2S S2I之类的数据转换函数 由于在lua引擎里 acb已经重载使用了这些转换 所以即用不上 也防止调用造成错误 所以干脆不注册  应该是吧

**Comment by w4454962** [comment]
async_hook 需要建立在 nf_register.cpp 的注册之前 也就是说  在地图运行后启动的base的话   这个cpp里的事件注册不会响应  
先加载 base的 hook
再加载 lua引擎里的hook
之后再来初始化 这个cpp 里面的注册 

你可以看我那个  我里面的解决方案是 没问题的  这个疑问可以关闭了

**Comment by luciouskami** [comment]
解决了，是没有搜到函数表的原因
